spring:
  datasource:
    url: jdbc:h2:file:./drone-db
    username: sa
    password: 123
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 100MB
management:
  endpoints:
    web:
      exposure:
        include=*:
application:
  battery-checker:
    fixed-delay: 5000
  maxMedicationWeights: 500


